import { type InsertTrainer } from "@shared/schema";

// Mock trainer data for certification verification
export const mockTrainers: InsertTrainer[] = [
  // Main requested trainer
  {
    firstName: "Kennard",
    lastName: "Love",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "32678964",
    issueDate: "2023-08-15",
  },
  // Other Love family members
  {
    firstName: "Marcus",
    lastName: "Love",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2023-445566",
    issueDate: "2023-06-10",
  },
  {
    firstName: "Diana",
    lastName: "Love",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-778899",
    issueDate: "2024-01-20",
  },
  {
    firstName: "Roberto",
    lastName: "Love",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-112233",
    issueDate: "2024-02-28",
  },
  // Additional diverse trainers
  {
    firstName: "John",
    lastName: "Smith",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-001234",
    issueDate: "2024-03-15",
  },
  {
    firstName: "Sarah",
    lastName: "Johnson",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-005678",
    issueDate: "2024-02-20",
  },
  {
    firstName: "Michael",
    lastName: "Davis",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-009876",
    issueDate: "2024-01-10",
  },
  {
    firstName: "Emily",
    lastName: "Rodriguez",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2023-887766",
    issueDate: "2023-11-05",
  },
  {
    firstName: "James",
    lastName: "Wilson",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-334455",
    issueDate: "2024-04-12",
  },
  {
    firstName: "Amanda",
    lastName: "Taylor",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2023-998877",
    issueDate: "2023-09-18",
  },
  {
    firstName: "Christopher",
    lastName: "Anderson",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-556677",
    issueDate: "2024-05-03",
  },
  {
    firstName: "Jessica",
    lastName: "Thomas",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2023-223344",
    issueDate: "2023-12-08",
  },
  {
    firstName: "David",
    lastName: "Jackson",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-445566",
    issueDate: "2024-03-25",
  },
  {
    firstName: "Lisa",
    lastName: "White",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2023-778899",
    issueDate: "2023-10-14",
  },
  {
    firstName: "Kevin",
    lastName: "Harris",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-112233",
    issueDate: "2024-06-17",
  },
  {
    firstName: "Michelle",
    lastName: "Martin",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2023-667788",
    issueDate: "2023-07-22",
  },
  {
    firstName: "Robert",
    lastName: "Thompson",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-889900",
    issueDate: "2024-04-30",
  },
  {
    firstName: "Nicole",
    lastName: "Garcia",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2023-445577",
    issueDate: "2023-08-07",
  },
  {
    firstName: "Brandon",
    lastName: "Martinez",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-223355",
    issueDate: "2024-02-14",
  },
  {
    firstName: "Stephanie",
    lastName: "Robinson",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2023-556688",
    issueDate: "2023-12-01",
  },
  {
    firstName: "Tyler",
    lastName: "Clark",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-889911",
    issueDate: "2024-05-20",
  },
  {
    firstName: "Rachel",
    lastName: "Lewis",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2023-334466",
    issueDate: "2023-09-05",
  },
  {
    firstName: "Anthony",
    lastName: "Lee",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-667799",
    issueDate: "2024-03-08",
  },
  {
    firstName: "Samantha",
    lastName: "Walker",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2023-112244",
    issueDate: "2023-11-28",
  },
  {
    firstName: "Daniel",
    lastName: "Hall",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-778800",
    issueDate: "2024-06-02",
  },
  {
    firstName: "Ashley",
    lastName: "Allen",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2023-445599",
    issueDate: "2023-10-30",
  },
  {
    firstName: "Matthew",
    lastName: "Young",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-223366",
    issueDate: "2024-01-15",
  },
  {
    firstName: "Lauren",
    lastName: "Hernandez",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2023-556699",
    issueDate: "2023-08-28",
  },
  {
    firstName: "Justin",
    lastName: "King",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-889922",
    issueDate: "2024-04-18",
  },
  {
    firstName: "Megan",
    lastName: "Wright",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2023-334477",
    issueDate: "2023-12-15",
  },
  {
    firstName: "Jordan",
    lastName: "Lopez",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2024-667788",
    issueDate: "2024-05-12",
  },
  {
    firstName: "Brittany",
    lastName: "Hill",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2023-112255",
    issueDate: "2023-09-20",
  },
  {
    firstName: "Cameron",
    lastName: "Scott",
    certificationType: "Human Movement Specialist (HMS)",
    certificationId: "HMS-2024-778811",
    issueDate: "2024-02-07",
  },
  {
    firstName: "Vanessa",
    lastName: "Green",
    certificationType: "Integrated Manual Therapist (IMT)",
    certificationId: "IMT-2023-445588",
    issueDate: "2023-11-12",
  },
  {
    firstName: "Trevor",
    lastName: "Adams",
    certificationType: "Certified Personal Trainer (CPT)",
    certificationId: "CPT-2024-223377",
    issueDate: "2024-06-25",
  },
];